"""
Membrane Database for PACE Calculation Module
Contains specifications for RO, NF, and UF elements.
"""

from typing import Dict, Any

class MembraneDatabase:
    # RO/NF Elements
    RO_MEMBRANES = {
        "BW30-400": {
            "type": "BWRO",
            "manufacturer": "DuPont",
            "active_area_m2": 37.2, # 400 sq ft
            "permeability_A": 2.5,  # L/m2/h/bar (approximate)
            "permeability_B": 1.5e-7, # m/s (TDS passage)
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.0,
            "max_feed_flow_m3h": 15.9,
            "min_conc_flow_m3h": 3.0,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            # Ion-specific Spiegler-Kedem Reflection Coefficients (sigma)
            "sigma": {
                "Ca": 0.996,
                "Mg": 0.996,
                "Na": 0.985,
                "K": 0.980,
                "Cl": 0.985,
                "SO4": 0.998,
                "HCO3": 0.980,
                "Ba": 0.997,
                "Sr": 0.997,
                "F": 0.970,
                "SiO2": 0.985,
                "B": 0.750,
                "NO3": 0.940,
                "PO4": 0.996,
                "NH4": 0.880
            }
        },
        "SW30HRLE-400": {
            "type": "SWRO",
            "manufacturer": "DuPont",
            "active_area_m2": 37.2,
            "permeability_A": 1.1,  # Lower A for SWRO
            "permeability_B": 4.5e-8, # Lower B (higher rejection)
            "feed_spacer_mil": 28,
            "max_pressure_bar": 82.7,
            "max_feed_flow_m3h": 17.0,
            "min_conc_flow_m3h": 3.0,
            "max_recovery_pct": 12.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "sigma": {
                "Ca": 0.999,
                "Mg": 0.999,
                "Na": 0.996,
                "K": 0.994,
                "Cl": 0.996,
                "SO4": 0.999,
                "HCO3": 0.994,
                "Ba": 0.999,
                "Sr": 0.999,
                "F": 0.990,
                "SiO2": 0.997,
                "B": 0.910,
                "NO3": 0.975,
                "PO4": 0.999,
                "NH4": 0.940
            }
        },
        "CPA5-LD": {
            "type": "BWRO",
            "manufacturer": "Hydranautics",
            "active_area_m2": 37.2,
            "permeability_A": 2.8,
            "permeability_B": 1.2e-7,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 17.0,
            "min_conc_flow_m3h": 3.2,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.990,
                "K": 0.985,
                "Cl": 0.990,
                "SO4": 0.998,
                "HCO3": 0.985,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.990,
                "B": 0.780,
                "NO3": 0.950,
                "PO4": 0.998,
                "NH4": 0.900
            }
        },
        "NF270-400": {
            "type": "NF",
            "manufacturer": "DuPont",
            "description": "High-permeability NF membrane; excellent divalent rejection, partial monovalent passage. FilmTec NF270-400/34i.",
            "active_area_m2": 37.2,
            "permeability_A": 7.60,       # L/m²/h/bar @ 25°C — spec Table 3
            "permeability_B": 5.80e-7,    # Ps_NaCl used as backward-compat B proxy (m/s)
            "E_Aw_over_R": 2640,          # Activation energy / R (K) — spec Table 3
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.0,
            "max_feed_flow_m3h": 15.9,
            "min_conc_flow_m3h": 0.9,     # 4 gpm — spec Table 1
            "max_recovery_pct": 20.0,     # Per-element recovery limit (NF operates at higher system recovery)
            "length_m": 1.016,
            "diameter_m": 0.201,
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "max_chlorine_mgL": 0.1,
            "max_sdi_15": 5.0,
            # Spiegler-Kedem reflection coefficients (σ) per ion — spec Tables 3 & 5
            # Group 1 (divalent anions): SO4, PO4  → σ = 0.960 (MgSO4 test)
            # Group 2 (divalent cations): Ca, Mg, Sr, Ba → σ = 0.780 (CaCl2 test)
            # Group 3 (monovalent ions): Na, K, Cl, F, NH4 → σ = 0.347 (NaCl test)
            # Group 4 (uncharged): SiO2, B → σ = 0.100
            # Specific values: HCO3 = 0.400, NO3 = 0.320 (Table 3)
            "sigma": {
                "Na":   0.347,  "K":   0.347,  "Cl":  0.347,
                "NO3":  0.320,  "F":   0.347,  "NH4": 0.347,
                "Ca":   0.780,  "Mg":  0.780,  "Sr":  0.780,
                "Ba":   0.780,  "Fe":  0.780,  "Mn":  0.780,
                "SO4":  0.960,  "PO4": 0.960,
                "HCO3": 0.400,
                "SiO2": 0.100,  "B":   0.100,  "Al":  0.347,
            },
            # Spiegler-Kedem solute permeabilities Ps (m/s) per ion — spec Tables 3 & 5
            "nf_ps": {
                "Na":   5.80e-7, "K":   5.80e-7, "Cl":  5.80e-7,
                "NO3":  6.10e-7, "F":   5.80e-7, "NH4": 5.80e-7,
                "Ca":   2.80e-7, "Mg":  2.80e-7, "Sr":  2.80e-7,
                "Ba":   2.80e-7, "Fe":  2.80e-7, "Mn":  2.80e-7,
                "SO4":  3.60e-8, "PO4": 3.60e-8,
                "HCO3": 4.20e-7,
                "SiO2": 1.20e-6, "B":   1.20e-6, "Al":  5.80e-7,
            }
        },
        "NF200-400": {
            "type": "NF",
            "manufacturer": "DuPont",
            "description": "Medium-tight NF membrane; moderate monovalent rejection, high divalent rejection. FilmTec NF200-400/34i.",
            "active_area_m2": 37.2,
            "permeability_A": 4.50,       # L/m²/h/bar @ 25°C — spec Table 3
            "permeability_B": 3.50e-7,    # Ps_NaCl as B proxy (m/s)
            "E_Aw_over_R": 2400,          # Activation energy / R (K) — spec Table 3
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.0,
            "max_feed_flow_m3h": 15.9,
            "min_conc_flow_m3h": 0.9,
            "max_recovery_pct": 20.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "max_chlorine_mgL": 0.1,
            "max_sdi_15": 5.0,
            "sigma": {
                "Na":   0.480,  "K":   0.480,  "Cl":  0.480,
                "NO3":  0.430,  "F":   0.480,  "NH4": 0.480,
                "Ca":   0.850,  "Mg":  0.850,  "Sr":  0.850,
                "Ba":   0.850,  "Fe":  0.850,  "Mn":  0.850,
                "SO4":  0.975,  "PO4": 0.975,
                "HCO3": 0.500,
                "SiO2": 0.150,  "B":   0.150,  "Al":  0.480,
            },
            "nf_ps": {
                "Na":   3.50e-7, "K":   3.50e-7, "Cl":  3.50e-7,
                "NO3":  3.90e-7, "F":   3.50e-7, "NH4": 3.50e-7,
                "Ca":   1.80e-7, "Mg":  1.80e-7, "Sr":  1.80e-7,
                "Ba":   1.80e-7, "Fe":  1.80e-7, "Mn":  1.80e-7,
                "SO4":  2.20e-8, "PO4": 2.20e-8,
                "HCO3": 2.80e-7,
                "SiO2": 8.00e-7, "B":   8.00e-7, "Al":  3.50e-7,
            }
        },
        "NF90-400": {
            "type": "NF",
            "manufacturer": "DuPont",
            "description": "Tight NF membrane; near-RO performance, high divalent and significant monovalent rejection. FilmTec NF90-400/34i.",
            "active_area_m2": 37.2,
            "permeability_A": 2.50,       # L/m²/h/bar @ 25°C — spec Table 3 (corrected from 4.5)
            "permeability_B": 8.00e-8,    # Ps_NaCl as B proxy (m/s)
            "E_Aw_over_R": 2640,          # Activation energy / R (K) — spec Table 3
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.0,
            "max_feed_flow_m3h": 15.9,
            "min_conc_flow_m3h": 0.9,
            "max_recovery_pct": 20.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "max_chlorine_mgL": 0.1,
            "max_sdi_15": 5.0,
            "sigma": {
                "Na":   0.870,  "K":   0.870,  "Cl":  0.870,
                "NO3":  0.820,  "F":   0.870,  "NH4": 0.870,
                "Ca":   0.950,  "Mg":  0.950,  "Sr":  0.950,
                "Ba":   0.950,  "Fe":  0.950,  "Mn":  0.950,
                "SO4":  0.995,  "PO4": 0.995,
                "HCO3": 0.780,
                "SiO2": 0.200,  "B":   0.200,  "Al":  0.870,
            },
            "nf_ps": {
                "Na":   8.00e-8, "K":   8.00e-8, "Cl":  8.00e-8,
                "NO3":  7.50e-8, "F":   8.00e-8, "NH4": 8.00e-8,
                "Ca":   4.00e-8, "Mg":  4.00e-8, "Sr":  4.00e-8,
                "Ba":   4.00e-8, "Fe":  4.00e-8, "Mn":  4.00e-8,
                "SO4":  5.00e-9, "PO4": 5.00e-9,
                "HCO3": 9.00e-8,
                "SiO2": 6.00e-7, "B":   6.00e-7, "Al":  8.00e-8,
            }
        },
        "HPA-4040": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "description": "Low fouling RO element with extended area for brackish water",
            "size": "4x40",
            "active_area_m2": 9.3,         # 100 ft2
            "permeability_A": 3.39,        # LMH/bar — derived from test conditions
            "permeability_B": 5.3e-8,      # m/s — derived from 99.6% rejection at test conditions
            "feed_spacer_mil": 34,         # typical for 4040 BWRO
            "max_pressure_bar": 41.4,      # 600 psi
            "max_feed_flow_m3h": 4.09,     # 18 gpm
            "min_conc_flow_m3h": 0.91,     # 4 gpm
            "max_recovery_pct": 15.0,
            "max_dp_per_element_bar": 1.03, # 15 psi
            "length_m": 1.016,             # 40 inches
            "diameter_m": 0.102,           # 4 inches
            "nominal_rejection": 0.996,
            "min_rejection": 0.995,
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "test_conditions": {
                "solute_ppm": 2000,
                "pressure_bar": 15.5,
                "temp_c": 25.0,
                "recovery_pct": 15.0
            },
            # Design flux guidelines by water source (from datasheet Page 2)
            # Values in LMH (converted from GFD: 1 GFD = 1.6985 LMH)
            "design_flux_guidelines": {
                "wastewater_conventional":   {"sdi_max": 5, "flux_min_lmh": 13.6, "flux_max_lmh": 20.4},
                "wastewater_uf_pretreated":  {"sdi_max": 3, "flux_min_lmh": 17.0, "flux_max_lmh": 23.8},
                "seawater_open_intake":      {"sdi_max": 5, "flux_min_lmh": 11.9, "flux_max_lmh": 17.0},
                "seawater_beach_well":       {"sdi_max": 3, "flux_min_lmh": 13.6, "flux_max_lmh": 20.4},
                "surface_water_sdi5":        {"sdi_max": 5, "flux_min_lmh": 20.4, "flux_max_lmh": 27.2},
                "surface_water_sdi3":        {"sdi_max": 3, "flux_min_lmh": 22.1, "flux_max_lmh": 28.9},
                "well_water":                {"sdi_max": 3, "flux_min_lmh": 22.1, "flux_max_lmh": 28.9},
                "ro_permeate":               {"sdi_max": 1, "flux_min_lmh": 35.7, "flux_max_lmh": 51.0}
            },
            # Saturation limits from datasheet
            "saturation_limits": {
                "LSI": 1.5,           # with antiscalant
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.990,
                "B": 0.770,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.890
            }
        },
        "HPA-RO-8040-LF-WW": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.367,
            "permeability_B": 3.89e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": ['LF'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPA-RO-8040": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.213,
            "permeability_B": 3.72e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPA-RO-LPM-8040-440": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 40.9,
            "permeability_A": 3.482,
            "permeability_B": 4.03e-08,
            "feed_spacer_mil": 28,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": ['LPM'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-BW-400": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.359,
            "permeability_B": 3.89e-08,
            "feed_spacer_mil": 31,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-LF": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.213,
            "permeability_B": 2.48e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['LF'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-LF2": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.52,
            "permeability_B": 2.71e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['LF'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-PRO-400": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.229,
            "permeability_B": 4.99e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.996,
            "min_rejection": 0.995,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "SWRO-8040-400": {
            "type": "SWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.5,
            "permeability_A": 1.075,
            "permeability_B": 1.76e-08,
            "feed_spacer_mil": 28,
            "max_pressure_bar": 55.2,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.995,
                "K": 0.983,
                "Cl": 0.995,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.85,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "SWRO-FR-8040-400": {
            "type": "SWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 1.183,
            "permeability_B": 1.93e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 55.2,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['FR'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.995,
                "K": 0.983,
                "Cl": 0.995,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.85,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "SWRO-HLE-8040-400": {
            "type": "SWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 1.297,
            "permeability_B": 2.12e-08,
            "feed_spacer_mil": 28,
            "max_pressure_bar": 55.2,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['HLE'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.995,
                "K": 0.983,
                "Cl": 0.995,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.85,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
    }

    # UF Modules
    UF_MODULES = {
        "IntegraTec-SFD-2880": {
            "type": "UF",
            "manufacturer": "DuPont", # Formerly Inge
            "membrane_area_m2": 80.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 85.0,
            "clean_tmp_max_bar": 1.0,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0 # LMH/bar at 20C (clean)
        },
        "SFP-2860": {
            "type": "UF",
            "manufacturer": "DuPont",
            "membrane_area_m2": 51.0,
            "fiber_id_mm": 0.7,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 80.0,
            "clean_tmp_max_bar": 1.0,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 140.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 8.0,
            "min_forward_flush_m3h": 1.0,
            "permeability_Lp20": 350.0
        }
    }

    @classmethod
    def get_ro_membrane(cls, name: str) -> Dict[str, Any]:
        raw_mem = cls.RO_MEMBRANES.get(name, cls.RO_MEMBRANES["BW30-400"])
        return cls._normalize_membrane(raw_mem)

    @classmethod
    def _normalize_membrane(cls, raw_mem: Dict[str, Any]) -> Dict[str, Any]:
        """
        Normalizes any catalog element into the 8.1 Membrane Datasheet Schema shape.
        """
        mem = raw_mem.copy()
        
        # 1. membrane_class
        mem["membrane_class"] = mem.get("type", "BWRO")
        
        # 2. operating_limits
        op_limits = mem.get("operating_limits", {})
        op_limits.setdefault("max_pressure", mem.get("max_pressure_bar"))
        op_limits.setdefault("max_temp", mem.get("max_temp_c"))
        op_limits.setdefault("ph_range", mem.get("ph_range"))
        op_limits.setdefault("cip_ph_range", mem.get("cip_ph_range"))
        op_limits.setdefault("max_chlorine", mem.get("max_chlorine_mgL"))
        op_limits.setdefault("max_sdi", mem.get("max_sdi_15"))
        mem["operating_limits"] = op_limits

        # 3. surface_class
        surf_class = mem.get("surface_class", {})
        flags = mem.get("flags", [])
        surf_class.setdefault("fouling_resistant_claim", "LF" in flags or "FR" in flags or "low fouling" in str(mem.get("description", "")).lower())
        surf_class.setdefault("hydrophilic", False)
        surf_class.setdefault("material", mem.get("material", "PA"))
        mem["surface_class"] = surf_class

        # 4. active_area, nominal_rejection, nominal_flow
        mem.setdefault("active_area", mem.get("active_area_m2"))
        mem.setdefault("nominal_rejection", mem.get("nominal_rejection"))
        mem.setdefault("nominal_flow", mem.get("max_feed_flow_m3h")) # Assuming max feed flow is a proxy if nominal flow missing

        # 5. design_flux_table and saturation_limits (already used in HPA-4040, map from guidelines)
        mem.setdefault("design_flux_table", mem.get("design_flux_guidelines", {}))
        default_sat = {
            "LSI": 1.5,
            "SDSI": 0.5,
            "CaSO4_pct": 230,
            "SrSO4_pct": 800,
            "BaSO4_pct": 6000,
            "SiO2_pct": 100
        }
        mem["saturation_limits"] = mem.get("saturation_limits") or default_sat

        return mem

    @classmethod
    def get_uf_module(cls, name: str) -> Dict[str, Any]:
        return cls.UF_MODULES.get(name, cls.UF_MODULES["IntegraTec-SFD-2880"])

    @classmethod
    def list_ro_membranes(cls):
        return [
            {
                "id": k,
                "name": k,
                "type": v.get("type"),
                "manufacturer": v.get("manufacturer"),
                "area": v.get("active_area_m2"),
                "feed_spacer_mil": v.get("feed_spacer_mil"),
                "nominal_rejection": v.get("nominal_rejection"),
                "max_pressure_bar": v.get("max_pressure_bar"),
                "max_feed_flow_m3h": v.get("max_feed_flow_m3h"),
                "min_conc_flow_m3h": v.get("min_conc_flow_m3h"),
                "max_recovery_pct": v.get("max_recovery_pct"),
                "length_m": v.get("length_m"),
                "diameter_m": v.get("diameter_m"),
                "material": v.get("material", "Polyamide Composite")
            }
            for k, v in cls.RO_MEMBRANES.items()
        ]

    @classmethod
    def list_uf_modules(cls):
        return [{"id": k, "name": k, "area": v["membrane_area_m2"]} for k, v in cls.UF_MODULES.items()]
