"""
Membrane Database for PACE Calculation Module
Contains specifications for RO, NF, and UF elements.
"""

from typing import Dict, Any

class MembraneDatabase:
    # RO/NF Elements
    RO_MEMBRANES = {
        "BW30-400": {
            "type": "BWRO",
            "manufacturer": "DuPont",
            "active_area_m2": 37.2, # 400 sq ft
            "permeability_A": 2.5,  # L/m2/h/bar (approximate)
            "permeability_B": 1.5e-7, # m/s (TDS passage)
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.0,
            "max_feed_flow_m3h": 15.9,
            "min_conc_flow_m3h": 3.0,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            # Ion-specific Spiegler-Kedem Reflection Coefficients (sigma)
            "sigma": {
                "Ca": 0.996,
                "Mg": 0.996,
                "Na": 0.985,
                "K": 0.980,
                "Cl": 0.985,
                "SO4": 0.998,
                "HCO3": 0.980,
                "Ba": 0.997,
                "Sr": 0.997,
                "F": 0.970,
                "SiO2": 0.985,
                "B": 0.750,
                "NO3": 0.940,
                "PO4": 0.996,
                "NH4": 0.880
            }
        },
        "SW30HRLE-400": {
            "type": "SWRO",
            "manufacturer": "DuPont",
            "active_area_m2": 37.2,
            "permeability_A": 1.1,  # Lower A for SWRO
            "permeability_B": 4.5e-8, # Lower B (higher rejection)
            "feed_spacer_mil": 28,
            "max_pressure_bar": 82.7,
            "max_feed_flow_m3h": 17.0,
            "min_conc_flow_m3h": 3.0,
            "max_recovery_pct": 12.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "sigma": {
                "Ca": 0.999,
                "Mg": 0.999,
                "Na": 0.996,
                "K": 0.994,
                "Cl": 0.996,
                "SO4": 0.999,
                "HCO3": 0.994,
                "Ba": 0.999,
                "Sr": 0.999,
                "F": 0.990,
                "SiO2": 0.997,
                "B": 0.910,
                "NO3": 0.975,
                "PO4": 0.999,
                "NH4": 0.940
            }
        },
        "CPA5-LD": {
            "type": "BWRO",
            "manufacturer": "Hydranautics",
            "active_area_m2": 37.2,
            "permeability_A": 2.8,
            "permeability_B": 1.2e-7,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 17.0,
            "min_conc_flow_m3h": 3.2,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.990,
                "K": 0.985,
                "Cl": 0.990,
                "SO4": 0.998,
                "HCO3": 0.985,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.990,
                "B": 0.780,
                "NO3": 0.950,
                "PO4": 0.998,
                "NH4": 0.900
            }
        },
        "NF90-400": {
            "type": "NF",
            "manufacturer": "DuPont",
            "active_area_m2": 37.2,
            "permeability_A": 4.5,  # Higher permeability
            "permeability_B": 8.0e-7, # Higher passage for monovalents
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.0,
            "max_feed_flow_m3h": 15.9,
            "min_conc_flow_m3h": 3.0,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "sigma": {
                "Ca": 0.980,   # High rejection of divalents
                "Mg": 0.980,
                "Na": 0.850,   # High passage of monovalents
                "K": 0.850,
                "Cl": 0.850,
                "SO4": 0.990,  # High rejection of divalents
                "HCO3": 0.800,
                "Ba": 0.985,
                "Sr": 0.985,
                "F": 0.800,
                "SiO2": 0.850,
                "B": 0.400,
                "NO3": 0.700,
                "PO4": 0.980,
                "NH4": 0.750
            }
        },
        "HPA-4040": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "description": "Low fouling RO element with extended area for brackish water",
            "size": "4x40",
            "active_area_m2": 9.3,         # 100 ft2
            "permeability_A": 3.39,        # LMH/bar — derived from test conditions
            "permeability_B": 5.3e-8,      # m/s — derived from 99.6% rejection at test conditions
            "feed_spacer_mil": 34,         # typical for 4040 BWRO
            "max_pressure_bar": 41.4,      # 600 psi
            "max_feed_flow_m3h": 4.09,     # 18 gpm
            "min_conc_flow_m3h": 0.91,     # 4 gpm
            "max_recovery_pct": 15.0,
            "max_dp_per_element_bar": 1.03, # 15 psi
            "length_m": 1.016,             # 40 inches
            "diameter_m": 0.102,           # 4 inches
            "nominal_rejection": 0.996,
            "min_rejection": 0.995,
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "test_conditions": {
                "solute_ppm": 2000,
                "pressure_bar": 15.5,
                "temp_c": 25.0,
                "recovery_pct": 15.0
            },
            # Design flux guidelines by water source (from datasheet Page 2)
            # Values in LMH (converted from GFD: 1 GFD = 1.6985 LMH)
            "design_flux_guidelines": {
                "wastewater_conventional":   {"sdi_max": 5, "flux_min_lmh": 13.6, "flux_max_lmh": 20.4},
                "wastewater_uf_pretreated":  {"sdi_max": 3, "flux_min_lmh": 17.0, "flux_max_lmh": 23.8},
                "seawater_open_intake":      {"sdi_max": 5, "flux_min_lmh": 11.9, "flux_max_lmh": 17.0},
                "seawater_beach_well":       {"sdi_max": 3, "flux_min_lmh": 13.6, "flux_max_lmh": 20.4},
                "surface_water_sdi5":        {"sdi_max": 5, "flux_min_lmh": 20.4, "flux_max_lmh": 27.2},
                "surface_water_sdi3":        {"sdi_max": 3, "flux_min_lmh": 22.1, "flux_max_lmh": 28.9},
                "well_water":                {"sdi_max": 3, "flux_min_lmh": 22.1, "flux_max_lmh": 28.9},
                "ro_permeate":               {"sdi_max": 1, "flux_min_lmh": 35.7, "flux_max_lmh": 51.0}
            },
            # Saturation limits from datasheet
            "saturation_limits": {
                "LSI": 1.5,           # with antiscalant
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.990,
                "B": 0.770,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.890
            }
        },
        "HPA-RO-8040-LF-WW": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.367,
            "permeability_B": 3.89e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": ['LF'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPA-RO-8040": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.213,
            "permeability_B": 3.72e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPA-RO-LPM-8040-440": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 40.9,
            "permeability_A": 3.482,
            "permeability_B": 4.03e-08,
            "feed_spacer_mil": 28,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": ['LPM'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-BW-400": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.359,
            "permeability_B": 3.89e-08,
            "feed_spacer_mil": 31,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-LF": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.213,
            "permeability_B": 2.48e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['LF'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-LF2": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.52,
            "permeability_B": 2.71e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['LF'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-PRO-400": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.229,
            "permeability_B": 4.99e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.996,
            "min_rejection": 0.995,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "SWRO-8040-400": {
            "type": "SWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.5,
            "permeability_A": 1.075,
            "permeability_B": 1.76e-08,
            "feed_spacer_mil": 28,
            "max_pressure_bar": 55.2,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.995,
                "K": 0.983,
                "Cl": 0.995,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.85,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "SWRO-FR-8040-400": {
            "type": "SWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 1.183,
            "permeability_B": 1.93e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 55.2,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['FR'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.995,
                "K": 0.983,
                "Cl": 0.995,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.85,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "SWRO-HLE-8040-400": {
            "type": "SWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 1.297,
            "permeability_B": 2.12e-08,
            "feed_spacer_mil": 28,
            "max_pressure_bar": 55.2,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['HLE'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.995,
                "K": 0.983,
                "Cl": 0.995,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.85,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
    }

    # UF Modules
    UF_MODULES = {
        "IntegraTec-SFD-2880": {
            "type": "UF",
            "manufacturer": "DuPont", # Formerly Inge
            "membrane_area_m2": 80.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 85.0,
            "clean_tmp_max_bar": 1.0,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0 # LMH/bar at 20C (clean)
        },
        "SFP-2860": {
            "type": "UF",
            "manufacturer": "DuPont",
            "membrane_area_m2": 51.0,
            "fiber_id_mm": 0.7,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 80.0,
            "clean_tmp_max_bar": 1.0,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 140.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 8.0,
            "min_forward_flush_m3h": 1.0,
            "permeability_Lp20": 350.0
        }
    }

    @classmethod
    def get_ro_membrane(cls, name: str) -> Dict[str, Any]:
        return cls.RO_MEMBRANES.get(name, cls.RO_MEMBRANES["BW30-400"])

    @classmethod
    def get_uf_module(cls, name: str) -> Dict[str, Any]:
        return cls.UF_MODULES.get(name, cls.UF_MODULES["IntegraTec-SFD-2880"])

    @classmethod
    def list_ro_membranes(cls):
        return [{"id": k, "name": k, "type": v["type"], "area": v["active_area_m2"]} for k, v in cls.RO_MEMBRANES.items()]

    @classmethod
    def list_uf_modules(cls):
        return [{"id": k, "name": k, "area": v["membrane_area_m2"]} for k, v in cls.UF_MODULES.items()]
