"""
Membrane Database for PACE Calculation Module
Contains specifications for RO, NF, and UF elements.
"""

from typing import Dict, Any

class MembraneDatabase:
    # RO/NF Elements
    RO_MEMBRANES = {
        "BW30-400": {
            "type": "BWRO",
            "manufacturer": "DuPont",
            "active_area_m2": 37.2, # 400 sq ft
            "permeability_A": 2.5,  # L/m2/h/bar (approximate)
            "permeability_B": 1.5e-7, # m/s (TDS passage)
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.0,
            "max_feed_flow_m3h": 15.9,
            "min_conc_flow_m3h": 3.0,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            # Ion-specific Spiegler-Kedem Reflection Coefficients (sigma)
            "sigma": {
                "Ca": 0.996,
                "Mg": 0.996,
                "Na": 0.985,
                "K": 0.980,
                "Cl": 0.985,
                "SO4": 0.998,
                "HCO3": 0.980,
                "Ba": 0.997,
                "Sr": 0.997,
                "F": 0.970,
                "SiO2": 0.985,
                "B": 0.750,
                "NO3": 0.940,
                "PO4": 0.996,
                "NH4": 0.880
            }
        },
        "SW30HRLE-400": {
            "type": "SWRO",
            "manufacturer": "DuPont",
            "active_area_m2": 37.2,
            "permeability_A": 1.1,  # Lower A for SWRO
            "permeability_B": 4.5e-8, # Lower B (higher rejection)
            "feed_spacer_mil": 28,
            "max_pressure_bar": 82.7,
            "max_feed_flow_m3h": 17.0,
            "min_conc_flow_m3h": 3.0,
            "max_recovery_pct": 12.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "sigma": {
                "Ca": 0.999,
                "Mg": 0.999,
                "Na": 0.996,
                "K": 0.994,
                "Cl": 0.996,
                "SO4": 0.999,
                "HCO3": 0.994,
                "Ba": 0.999,
                "Sr": 0.999,
                "F": 0.990,
                "SiO2": 0.997,
                "B": 0.910,
                "NO3": 0.975,
                "PO4": 0.999,
                "NH4": 0.940
            }
        },
        "CPA5-LD": {
            "type": "BWRO",
            "manufacturer": "Hydranautics",
            "active_area_m2": 37.2,
            "permeability_A": 2.8,
            "permeability_B": 1.2e-7,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 17.0,
            "min_conc_flow_m3h": 3.2,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.990,
                "K": 0.985,
                "Cl": 0.990,
                "SO4": 0.998,
                "HCO3": 0.985,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.990,
                "B": 0.780,
                "NO3": 0.950,
                "PO4": 0.998,
                "NH4": 0.900
            }
        },
"HPA-4040": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "description": "Low fouling RO element with extended area for brackish water",
            "size": "4x40",
            "active_area_m2": 9.3,         # 100 ft2
            "permeability_A": 3.39,        # LMH/bar — derived from test conditions
            "permeability_B": 5.3e-8,      # m/s — derived from 99.6% rejection at test conditions
            "feed_spacer_mil": 34,         # typical for 4040 BWRO
            "max_pressure_bar": 41.4,      # 600 psi
            "max_feed_flow_m3h": 4.09,     # 18 gpm
            "min_conc_flow_m3h": 0.91,     # 4 gpm
            "max_recovery_pct": 15.0,
            "max_dp_per_element_bar": 1.03, # 15 psi
            "length_m": 1.016,             # 40 inches
            "diameter_m": 0.102,           # 4 inches
            "nominal_rejection": 0.996,
            "min_rejection": 0.995,
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "test_conditions": {
                "solute_ppm": 2000,
                "pressure_bar": 15.5,
                "temp_c": 25.0,
                "recovery_pct": 15.0
            },
            # Design flux guidelines by water source (from datasheet Page 2)
            # Values in LMH (converted from GFD: 1 GFD = 1.6985 LMH)
            "design_flux_guidelines": {
                "wastewater_conventional":   {"sdi_max": 5, "flux_min_lmh": 13.6, "flux_max_lmh": 20.4},
                "wastewater_uf_pretreated":  {"sdi_max": 3, "flux_min_lmh": 17.0, "flux_max_lmh": 23.8},
                "seawater_open_intake":      {"sdi_max": 5, "flux_min_lmh": 11.9, "flux_max_lmh": 17.0},
                "seawater_beach_well":       {"sdi_max": 3, "flux_min_lmh": 13.6, "flux_max_lmh": 20.4},
                "surface_water_sdi5":        {"sdi_max": 5, "flux_min_lmh": 20.4, "flux_max_lmh": 27.2},
                "surface_water_sdi3":        {"sdi_max": 3, "flux_min_lmh": 22.1, "flux_max_lmh": 28.9},
                "well_water":                {"sdi_max": 3, "flux_min_lmh": 22.1, "flux_max_lmh": 28.9},
                "ro_permeate":               {"sdi_max": 1, "flux_min_lmh": 35.7, "flux_max_lmh": 51.0}
            },
            # Saturation limits from datasheet
            "saturation_limits": {
                "LSI": 1.5,           # with antiscalant
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.990,
                "B": 0.770,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.890
            }
        },
        "HPA-RO-8040-LF-WW": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.367,
            "permeability_B": 3.89e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": ['LF'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPA-RO-8040": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.213,
            "permeability_B": 3.72e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPA-RO-LPM-8040-440": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 40.9,
            "permeability_A": 3.482,
            "permeability_B": 4.03e-08,
            "feed_spacer_mil": 28,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": ['LPM'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-BW-400": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.359,
            "permeability_B": 3.89e-08,
            "feed_spacer_mil": 31,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.997,
            "min_rejection": 0.9960000000000001,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-LF": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.213,
            "permeability_B": 2.48e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['LF'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-LF2": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.52,
            "permeability_B": 2.71e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['LF'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "HPARO-8040-PRO-400": {
            "type": "BWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 3.229,
            "permeability_B": 4.99e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 41.4,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.996,
            "min_rejection": 0.995,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.988,
                "K": 0.983,
                "Cl": 0.988,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.77,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "SWRO-8040-400": {
            "type": "SWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.5,
            "permeability_A": 1.075,
            "permeability_B": 1.76e-08,
            "feed_spacer_mil": 28,
            "max_pressure_bar": 55.2,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": [],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.995,
                "K": 0.983,
                "Cl": 0.995,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.85,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "SWRO-FR-8040-400": {
            "type": "SWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 1.183,
            "permeability_B": 1.93e-08,
            "feed_spacer_mil": 34,
            "max_pressure_bar": 55.2,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['FR'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.995,
                "K": 0.983,
                "Cl": 0.995,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.85,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
        "SWRO-HLE-8040-400": {
            "type": "SWRO",
            "manufacturer": "Permionics",
            "active_area_m2": 37.2,
            "permeability_A": 1.297,
            "permeability_B": 2.12e-08,
            "feed_spacer_mil": 28,
            "max_pressure_bar": 55.2,
            "max_feed_flow_m3h": 16.0,
            "min_conc_flow_m3h": 4.5,
            "max_recovery_pct": 15.0,
            "length_m": 1.016,
            "diameter_m": 0.201,
            "nominal_rejection": 0.998,
            "min_rejection": 0.997,
            "flags": ['HLE'],
            "max_temp_c": 45.0,
            "ph_range": [2.0, 11.0],
            "cip_ph_range": [1.0, 13.0],
            "max_turbidity_ntu": 1.0,
            "max_sdi_15": 5.0,
            "max_chlorine_mgL": 0.1,
            "design_flux_guidelines": {
                "wastewater_conventional": {'sdi_max': 5, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "wastewater_uf_pretreated": {'sdi_max': 3, 'flux_min_lmh': 17.0, 'flux_max_lmh': 23.8},
                "seawater_open_intake": {'sdi_max': 5, 'flux_min_lmh': 11.9, 'flux_max_lmh': 17.0},
                "seawater_beach_well": {'sdi_max': 3, 'flux_min_lmh': 13.6, 'flux_max_lmh': 20.4},
                "surface_water_sdi5": {'sdi_max': 5, 'flux_min_lmh': 20.4, 'flux_max_lmh': 27.2},
                "surface_water_sdi3": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "well_water": {'sdi_max': 3, 'flux_min_lmh': 22.1, 'flux_max_lmh': 28.9},
                "ro_permeate": {'sdi_max': 1, 'flux_min_lmh': 35.7, 'flux_max_lmh': 51.0},
            },
            "saturation_limits": {
                "LSI": 1.5,
                "SDSI": 0.5,
                "CaSO4_pct": 230,
                "SrSO4_pct": 800,
                "BaSO4_pct": 6000,
                "SiO2_pct": 100,
            },
            "sigma": {
                "Ca": 0.997,
                "Mg": 0.997,
                "Na": 0.995,
                "K": 0.983,
                "Cl": 0.995,
                "SO4": 0.998,
                "HCO3": 0.983,
                "Ba": 0.998,
                "Sr": 0.998,
                "F": 0.975,
                "SiO2": 0.99,
                "B": 0.85,
                "NO3": 0.945,
                "PO4": 0.997,
                "NH4": 0.89,
            },
        },
    }

    # UF Modules
    UF_MODULES = {
        "PERMA-UF-i0875s40": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 40.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 200.0,
            "design_flux_lmh": 40.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-iH0860": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 40.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 200.0,
            "design_flux_lmh": 40.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-0697": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 50.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 30.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-i1066": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 50.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 200.0,
            "design_flux_lmh": 40.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-2860T": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 51.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 35.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-i0975": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 55.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 200.0,
            "design_flux_lmh": 40.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-0776": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 56.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 135.0,
            "design_flux_lmh": 30.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-i1066X": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 60.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 200.0,
            "design_flux_lmh": 40.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-i0876s": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 64.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 200.0,
            "design_flux_lmh": 40.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-0697X": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 65.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 30.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-iP70": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 70.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 200.0,
            "design_flux_lmh": 40.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-2880T": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 77.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 35.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-2880": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 77.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 30.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-P77": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 77.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 30.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-2880X": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 80.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 120.0,
            "design_flux_lmh": 30.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-i1077": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 80.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 180.0,
            "design_flux_lmh": 50.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-iP80": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 80.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 200.0,
            "design_flux_lmh": 40.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-i1183": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 81.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 180.0,
            "design_flux_lmh": 50.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-1075T": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 120.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 135.0,
            "design_flux_lmh": 35.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
        "PERMA-UF-0992": {
            "type": "UF",
            "manufacturer": "Permionics",
            "membrane_area_m2": 60.0,
            "fiber_id_mm": 0.8,
            "max_filtration_flux_lmh": 180.0,
            "design_flux_lmh": 30.0,
            "clean_tmp_max_bar": 1.2,
            "fouled_tmp_max_bar": 2.1,
            "max_tmp_bar": 2.5,
            "backwash_flux_lmh": 150.0,
            "backwash_duration_s": 45,
            "air_scour_flow_m3h": 12.0,
            "min_forward_flush_m3h": 1.5,
            "permeability_Lp20": 400.0,
            "unit_cost_inr": 100000.0,
            "feed_pump_kw_per_module": 0.75,
            "backwash_pump_kw_per_module": 1.1,
        },
    }


    @classmethod
    def get_ro_membrane(cls, name: str) -> Dict[str, Any]:
        raw_mem = cls.RO_MEMBRANES.get(name, cls.RO_MEMBRANES["BW30-400"])
        return cls._normalize_membrane(raw_mem)

    @classmethod
    def _normalize_membrane(cls, raw_mem: Dict[str, Any]) -> Dict[str, Any]:
        """
        Normalizes any catalog element into the 8.1 Membrane Datasheet Schema shape.
        """
        mem = raw_mem.copy()
        
        # 1. membrane_class
        mem["membrane_class"] = mem.get("type", "BWRO")
        
        # 2. operating_limits
        op_limits = mem.get("operating_limits", {})
        op_limits.setdefault("max_pressure", mem.get("max_pressure_bar"))
        op_limits.setdefault("max_temp", mem.get("max_temp_c"))
        op_limits.setdefault("ph_range", mem.get("ph_range"))
        op_limits.setdefault("cip_ph_range", mem.get("cip_ph_range"))
        op_limits.setdefault("max_chlorine", mem.get("max_chlorine_mgL"))
        op_limits.setdefault("max_sdi", mem.get("max_sdi_15"))
        mem["operating_limits"] = op_limits

        # 3. surface_class
        surf_class = mem.get("surface_class", {})
        flags = mem.get("flags", [])
        surf_class.setdefault("fouling_resistant_claim", "LF" in flags or "FR" in flags or "low fouling" in str(mem.get("description", "")).lower())
        surf_class.setdefault("hydrophilic", False)
        surf_class.setdefault("material", mem.get("material", "PA"))
        mem["surface_class"] = surf_class

        # 4. active_area, nominal_rejection, nominal_flow
        mem.setdefault("active_area", mem.get("active_area_m2"))
        mem.setdefault("nominal_rejection", mem.get("nominal_rejection"))
        mem.setdefault("nominal_flow", mem.get("max_feed_flow_m3h")) # Assuming max feed flow is a proxy if nominal flow missing

        # 5. design_flux_table and saturation_limits (already used in HPA-4040, map from guidelines)
        mem.setdefault("design_flux_table", mem.get("design_flux_guidelines", {}))
        default_sat = {
            "LSI": 1.5,
            "SDSI": 0.5,
            "CaSO4_pct": 230,
            "SrSO4_pct": 800,
            "BaSO4_pct": 6000,
            "SiO2_pct": 100
        }
        mem["saturation_limits"] = mem.get("saturation_limits") or default_sat

        return mem

    @classmethod
    def get_uf_module(cls, name: str) -> Dict[str, Any]:
        return cls.UF_MODULES.get(name, cls.UF_MODULES["PERMA-UF-i0875s40"])

    @classmethod
    def list_ro_membranes(cls):
        return [
            {
                "id": k,
                "name": k,
                "type": v.get("type"),
                "manufacturer": v.get("manufacturer"),
                "area": v.get("active_area_m2"),
                "feed_spacer_mil": v.get("feed_spacer_mil"),
                "nominal_rejection": v.get("nominal_rejection"),
                "max_pressure_bar": v.get("max_pressure_bar"),
                "max_feed_flow_m3h": v.get("max_feed_flow_m3h"),
                "min_conc_flow_m3h": v.get("min_conc_flow_m3h"),
                "max_recovery_pct": v.get("max_recovery_pct"),
                "length_m": v.get("length_m"),
                "diameter_m": v.get("diameter_m"),
                "material": v.get("material", "Polyamide Composite")
            }
            for k, v in cls.RO_MEMBRANES.items()
        ]

    @classmethod
    def list_uf_modules(cls):
        return [{"id": k, "name": k, "area": v["membrane_area_m2"]} for k, v in cls.UF_MODULES.items()]
