"""
Report Generator for PACE Calculation Module
Generates a detailed Word document matching the industry reference reports.
"""
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

class ReportGenerator:
    def __init__(self):
        pass

    def _add_table_with_borders(self, doc, headers, rows):
        table = doc.add_table(rows=1 + len(rows), cols=len(headers))
        table.style = 'Light Grid Accent 1'
        
        for i, h in enumerate(headers):
            cell = table.rows[0].cells[i]
            cell.text = h
            for run in cell.paragraphs[0].runs:
                run.bold = True
                
        for ri, row in enumerate(rows):
            for ci, val in enumerate(row):
                cell = table.rows[ri + 1].cells[ci]
                cell.text = str(val)
        return table

    def generate_calculation_report(self, system_results: dict, output_path: str = "Calculation_Report.docx"):
        """
        Generates a comprehensive design report.
        """
        doc = Document()
        
        # Title
        title = doc.add_heading("System Design Calculation Report", level=1)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph("Generated by PACE Engineering Module\n")
        
        # System Overview
        doc.add_heading("1. System Overview", level=2)
        train = system_results.get("technology_train", "Unknown")
        
        # Check if recycle is enabled
        recycle = system_results.get("recycle")
        overall_rec_pct = system_results.get('ro_results', {}).get('summary', {}).get('total_recovery', 0)*100
        if recycle and recycle.get("enabled"):
            overall_rec_pct = recycle.get("effective_system_recovery_pct", overall_rec_pct)

        overview_data = [
            ["Technology Train:", train],
            ["Target Product Flow:", f"{system_results.get('ro_results', {}).get('summary', {}).get('perm_flow', 0):.2f} m³/h"],
            ["Overall Recovery:", f"{overall_rec_pct:.1f} %"]
        ]
        self._add_table_with_borders(doc, ["Parameter", "Value"], overview_data)

        if recycle and recycle.get("enabled"):
            doc.add_heading("Concentrate Recycle Summary", level=3)
            rec_data = [
                ["Recycle Ratio:", f"{recycle.get('recycle_ratio', 0)*100:.1f} %"],
                ["Recycle Flow:", f"{recycle.get('recycle_flow_m3h', 0):.2f} m³/h"],
                ["Blended Feed Flow:", f"{recycle.get('blended_feed_flow_m3h', 0):.2f} m³/h"],
                ["Blended Feed TDS:", f"{recycle.get('blended_feed_tds_mg_l', 0):.0f} mg/L"],
                ["Iterations to Converge:", str(recycle.get('iterations_to_converge', 1))]
            ]
            self._add_table_with_borders(doc, ["Parameter", "Value"], rec_data)
        
        # UF Section
        if "UF" in train and system_results.get("uf_results"):
            doc.add_heading("2. Ultrafiltration (UF) System", level=2)
            uf = system_results["uf_results"]
            
            doc.add_heading("System Overview", level=3)
            uf_overview = [
                ["Module Type", uf["overview"]["module_type"]],
                ["Total Modules", str(uf["overview"]["total_modules"])],
                ["Gross Feed", f"{uf['overview']['gross_feed_m3h']} m³/h"],
                ["Recovery", f"{uf['overview']['recovery_pct']} %"],
                ["Design TMP", f"{uf['overview']['tmp_design_bar']} bar"]
            ]
            self._add_table_with_borders(doc, ["Parameter", "Value"], uf_overview)
            
            doc.add_heading("Operating Conditions", level=3)
            uf_ops = [
                ["Filtration Flux", f"{uf['operating_conditions']['filtration_flux_lmh']} LMH"],
                ["Backwash Flux", f"{uf['operating_conditions']['backwash_flux_lmh']} LMH"],
                ["Backwash Duration", f"{uf['operating_conditions']['backwash_duration_min']} min"],
                ["CEB Interval", f"{uf['operating_conditions']['acid_ceb_interval_h']} hours"]
            ]
            self._add_table_with_borders(doc, ["Condition", "Value"], uf_ops)
            
        # RO Section
        if ("RO" in train or "NF" in train) and system_results.get("ro_results"):
            doc.add_heading("3. Reverse Osmosis (RO) System", level=2)
            ro = system_results["ro_results"]
            
            ro_overview = [
                ["Feed Flow", f"{ro['summary']['feed_flow']:.2f} m³/h"],
                ["Permeate Flow", f"{ro['summary']['perm_flow']:.2f} m³/h"],
                ["Concentrate Flow", f"{ro['summary']['conc_flow']:.2f} m³/h"],
                ["Feed Pressure", f"{ro['summary']['feed_pressure_bar']:.1f} bar"],
                ["Average Flux", f"{ro['summary']['avg_flux_lmh']:.1f} LMH"],
                ["Specific Energy", f"{ro['summary']['sec_kwh_m3']:.2f} kWh/m³"]
            ]
            self._add_table_with_borders(doc, ["Parameter", "Value"], ro_overview)
            
            doc.add_heading("Element-wise Performance", level=3)
            elem_headers = ["Element", "Feed Flow (m³/h)", "Perm Flow (m³/h)", "Conc Flow (m³/h)", "Feed Press (bar)", "ΔP (bar)", "Flux (LMH)", "Rec %"]
            elem_rows = []
            
            vessels_per_stage = ro["summary"].get("vessels_per_stage", [])
            stages_count = len(vessels_per_stage) if vessels_per_stage else 1
            
            for stage_idx in range(stages_count):
                num_vessels = vessels_per_stage[stage_idx] if stage_idx < len(vessels_per_stage) else 1
                stage_elements = [e for e in ro["elements"] if e["stage"] == (stage_idx + 1)]
                
                for v in range(1, num_vessels + 1):
                    for e in stage_elements:
                        elem_rows.append([
                            f"S{e['stage']}-V{v}-E{e['position']}",
                            f"{e['feed_flow']:.2f}",
                            f"{e['perm_flow']:.3f}",
                            f"{e['conc_flow']:.2f}",
                            f"{e['feed_pressure']:.1f}",
                            f"{e['dp']:.2f}",
                            f"{e['flux']:.1f}",
                            f"{e['recovery']*100:.1f}"
                        ])
            self._add_table_with_borders(doc, elem_headers, elem_rows)
            
            doc.add_heading("Ion Rejection Profile", level=3)
            ion_headers = ["Ion", "Feed (mg/L)", "Permeate (mg/L)", "Reject (mg/L)", "Rejection (%)"]
            ion_rows = []
            
            ion_map = {
                'Ca': 'calcium', 'Mg': 'magnesium', 'Na': 'sodium', 'K': 'potassium',
                'Ba': 'barium', 'Sr': 'strontium', 'Cl': 'chloride', 'SO4': 'sulfate',
                'HCO3': 'bicarbonate', 'NO3': 'nitrate', 'F': 'fluoride', 'SiO2': 'silica',
                'B': 'boron', 'PO4': 'phosphate', 'NH4': 'ammonium', 'Al': 'aluminium',
                'Fe': 'iron', 'Mn': 'manganese'
            }
            feed_tds = ro['summary']['feed_tds']
            for ion, perm_c in ro['summary']['perm_ions'].items():
                feed_key = ion_map.get(ion, ion.lower())
                feed_c = system_results["feed_water_used"].get(feed_key, 0)
                conc_c = ro['summary']['conc_ions'].get(ion, 0)
                rej = (1 - (perm_c / feed_c))*100 if feed_c > 0 else 0
                
                ion_rows.append([
                    ion,
                    f"{feed_c:.2f}",
                    f"{perm_c:.3f}",
                    f"{conc_c:.2f}",
                    f"{rej:.2f}"
                ])
            self._add_table_with_borders(doc, ion_headers, ion_rows)

        # Warnings Section
        doc.add_heading("4. Design Warnings", level=2)
        all_warnings = []
        if system_results.get("uf_results") and system_results["uf_results"].get("warnings"):
            all_warnings.extend(system_results["uf_results"]["warnings"])
        if system_results.get("ro_results") and system_results["ro_results"].get("warnings"):
            all_warnings.extend(system_results["ro_results"]["warnings"])
            
        if all_warnings:
            warn_headers = ["Type", "Limit", "Estimate", "Status"]
            warn_rows = []
            for w in all_warnings:
                warn_rows.append([
                    w["type"],
                    str(w.get("limit", "-")),
                    f"{w.get('estimate', w.get('value', 0)):.2f}",
                    w.get("status", "FAIL")
                ])
            self._add_table_with_borders(doc, warn_headers, warn_rows)
        else:
            doc.add_paragraph("No design warnings. All parameters within manufacturer limits.")

        doc.save(output_path)
        return output_path
